//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "models")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub driver: String,
    pub make_id: i32,
    pub active: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::makes::Entity",
        from = "Column::MakeId",
        to = "super::makes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Makes,
    #[sea_orm(has_many = "super::printers::Entity")]
    Printers,
}

impl Related<super::makes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Makes.def()
    }
}

impl Related<super::printers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Printers.def()
    }
}
