//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::locations::Entity as Locations;
pub use super::makes::Entity as Makes;
pub use super::models::Entity as Models;
pub use super::notes::Entity as Notes;
pub use super::printers::Entity as Printers;
pub use super::users::Entity as Users;
